node:
    image: mikemichel/wercker2sloppy:4407f3b462d6bbb58013656553a3f594ed91ca8b
    environment:
      - MONGODB_URI=mongodb://mongodb/todo
    links:
      - mongodb     
    ports: 
      - 5000:5000
mongodb:
  image: mongo
  ports:
     - 27015
